
export enum SkillType {
    Language = 'language',
    Framework = 'framework',
    Platform = 'platform',
    // Tool = 'tool', // Example for future extension
}

export interface ProjectImage {
    url: string;
    alt?: string;
    caption?: string;
}

export interface Skill {
    id: string; // To be generated by dynamo table.
    name: string;
    displayText: string;
    lucideIconName: string;
    type: SkillType
}

export interface Project {
    id: string; // To be generated by dynamo table.
    name: string;
    desc: string;
    images: ProjectImage[];
    video: string;
    skills: string[]; // List of skills id's used in project.
    githubUrl: string;
    demoUrl: string;
    isFeatured: boolean;
    createdAt: string; // To be generated by dynamo table.
    updatedAt: string; // To be generated by dynamo table.
    status: 'published' | 'draft';
}

